import { Asset, Allocation, Repair, WarrantyTracking, User, KPIData } from './types';

export const mockAssets: Asset[] = [
  {
    id: 'AST001',
    name: 'Dell Latitude 5540',
    sku: 'DL-5540-001',
    category: 'Computing',
    subcategory: 'Laptops',
    status: 'allocated',
    location: 'Office A',
    purchaseDate: '2022-03-15',
    purchasePrice: 1200,
    currentValue: 800,
    warrantyExpiry: '2025-03-15',
    description: 'Business laptop for development team',
    imageUrl: '/assets/laptop.jpg',
  },
  {
    id: 'AST002',
    name: 'HP ProBook 450',
    sku: 'HP-450-002',
    category: 'Computing',
    subcategory: 'Laptops',
    status: 'available',
    location: 'Warehouse',
    purchaseDate: '2023-06-20',
    purchasePrice: 950,
    currentValue: 900,
    warrantyExpiry: '2026-06-20',
  },
  {
    id: 'AST003',
    name: 'Monitor LG 27"',
    sku: 'LG-27-003',
    category: 'Peripherals',
    subcategory: 'Monitors',
    status: 'allocated',
    location: 'Office B',
    purchaseDate: '2021-11-10',
    purchasePrice: 350,
    currentValue: 250,
    warrantyExpiry: '2024-11-10',
    description: '4K display monitor',
  },
  {
    id: 'AST004',
    name: 'Keyboard Mechanical RGB',
    sku: 'KEY-RGB-004',
    category: 'Peripherals',
    subcategory: 'Keyboards',
    status: 'damaged',
    location: 'Warehouse',
    purchaseDate: '2022-01-05',
    purchasePrice: 150,
    currentValue: 0,
  },
  {
    id: 'AST005',
    name: 'Router Cisco C3850',
    sku: 'CSC-3850-005',
    category: 'Network',
    subcategory: 'Routers',
    status: 'allocated',
    location: 'Server Room',
    purchaseDate: '2020-08-12',
    purchasePrice: 2500,
    currentValue: 1500,
    warrantyExpiry: '2025-08-12',
  },
  {
    id: 'AST006',
    name: 'UPS System 10KVA',
    sku: 'UPS-10K-006',
    category: 'Power',
    subcategory: 'UPS',
    status: 'repair',
    location: 'Service Center',
    purchaseDate: '2019-02-20',
    purchasePrice: 5000,
    currentValue: 2000,
  },
  {
    id: 'AST007',
    name: 'Mouse Logitech MX',
    sku: 'LOG-MX-007',
    category: 'Peripherals',
    subcategory: 'Mouse',
    status: 'available',
    location: 'Warehouse',
    purchaseDate: '2023-09-15',
    purchasePrice: 100,
    currentValue: 95,
  },
  {
    id: 'AST008',
    name: 'Server Dell R750',
    sku: 'DELL-R750-008',
    category: 'Computing',
    subcategory: 'Servers',
    status: 'allocated',
    location: 'Data Center',
    purchaseDate: '2021-04-10',
    purchasePrice: 8000,
    currentValue: 5000,
    warrantyExpiry: '2026-04-10',
  },
];

export const mockAllocations: Allocation[] = [
  {
    id: 'ALLOC001',
    assetId: 'AST001',
    employeeId: 'EMP001',
    employeeName: 'John Smith',
    department: 'Engineering',
    allocatedDate: '2024-01-15',
    dueReturnDate: '2025-12-31',
    status: 'active',
  },
  {
    id: 'ALLOC002',
    assetId: 'AST003',
    employeeId: 'EMP002',
    employeeName: 'Sarah Johnson',
    department: 'Design',
    allocatedDate: '2024-02-20',
    dueReturnDate: '2025-12-31',
    status: 'active',
  },
  {
    id: 'ALLOC003',
    assetId: 'AST005',
    employeeId: 'EMP003',
    employeeName: 'Mike Brown',
    department: 'IT Operations',
    allocatedDate: '2023-08-10',
    status: 'active',
  },
];

export const mockRepairs: Repair[] = [
  {
    id: 'REP001',
    assetId: 'AST006',
    assetName: 'UPS System 10KVA',
    reportedDate: '2024-05-10',
    description: 'Battery backup not holding charge',
    status: 'in_progress',
    vendor: 'TechCare Services',
    cost: 800,
    notes: 'Ordered replacement batteries',
  },
  {
    id: 'REP002',
    assetId: 'AST004',
    assetName: 'Keyboard Mechanical RGB',
    reportedDate: '2024-04-15',
    description: 'Keys not responding, water damage',
    status: 'closed',
    vendor: 'TechCare Services',
    cost: 0,
    completedDate: '2024-04-20',
    notes: 'Not economical to repair, marked for scrap',
  },
];

export const mockWarrantyTracking: WarrantyTracking[] = [
  {
    id: 'WARR001',
    assetId: 'AST001',
    assetName: 'Dell Latitude 5540',
    expiryDate: '2025-03-15',
    daysRemaining: 245,
    status: 'active',
    vendor: 'Dell',
    type: 'Hardware',
  },
  {
    id: 'WARR002',
    assetId: 'AST002',
    assetName: 'HP ProBook 450',
    expiryDate: '2026-06-20',
    daysRemaining: 531,
    status: 'active',
    vendor: 'HP',
    type: 'Hardware',
  },
  {
    id: 'WARR003',
    assetId: 'AST003',
    assetName: 'Monitor LG 27"',
    expiryDate: '2024-11-10',
    daysRemaining: -31,
    status: 'expired',
    vendor: 'LG',
    type: 'Hardware',
  },
];

export const mockUsers: User[] = [
  {
    id: 'USER001',
    email: 'admin@company.com',
    name: 'Admin User',
    role: 'admin',
    createdAt: '2023-01-01',
  },
  {
    id: 'USER002',
    email: 'manager@company.com',
    name: 'Manager User',
    role: 'manager',
    department: 'IT',
    createdAt: '2023-06-15',
  },
  {
    id: 'USER003',
    email: 'employee@company.com',
    name: 'Employee User',
    role: 'employee',
    department: 'Engineering',
    createdAt: '2024-01-10',
  },
];

export const mockKPIData: KPIData = {
  totalAssets: 8,
  allocatedAssets: 4,
  availableStock: 2,
  inRepair: 1,
  warrantyAlerts: 1,
  damagedAssets: 1,
  scrapAssets: 0,
};
